'use strict';
const assert=require('node:assert/strict'),C=require('../account-core.js');
const A='123e4567-e89b-42d3-a456-426614174000',B='123e4567-e89b-42d3-a456-426614174001',at='2026-10-08T12:00:00Z';
function raw(seed={}){const m=new Map(Object.entries(seed));return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k),key:i=>[...m.keys()][i]??null,get length(){return m.size},m};}
const store=v=>raw(Object.fromEntries(Object.entries(v).map(([k,x])=>[k,JSON.stringify(x)])));
const item=(name='One')=>({symbol:'AAPL',name});
const record=(value=item(),revision=1,deleted=false)=>({user_id:A,kind:'watchlist',record_key:'AAPL',payload:deleted?null:value,deleted,revision,created_at:at,updated_at:at});
const local=(value=item())=>C.collect(store({sq_watchlist:value?[value]:[]}));
const remote=(value=item(),revision=1,deleted=false)=>C.rowsMap([record(value,revision,deleted)],A);
let count=0;function test(name,fn){fn();console.log('PASS Account:',name);count++;}
test('guest, account A and account B keep separate data and journals',()=>{const r=raw(),g=C.createStore(r,null),a=C.createStore(r,A),b=C.createStore(r,B);g.setItem('sq_watchlist','guest');g.setItem('sq_research_checkins_v1','GUEST_JOURNAL');a.setItem('sq_watchlist','A');a.setItem('sq_research_checkins_v1','A_JOURNAL');b.setItem('sq_watchlist','B');assert.equal(g.getItem('sq_watchlist'),'guest');assert.equal(a.getItem('sq_watchlist'),'A');assert.equal(b.getItem('sq_watchlist'),'B');assert.equal(b.getItem('sq_research_checkins_v1'),null);assert.equal(g.getItem('sq_research_checkins_v1'),'GUEST_JOURNAL');assert.throws(()=>C.createStore(r,'wrong'));});
test('only explicit account categories are projected',()=>{const s=store({sq_watchlist:[item()],sq_studio_preferences_v1:{name:'LOCAL_NAME',theme:'quiet'},sq_research_checkins_v1:{entries:[{reason:'PRIVATE_JOURNAL_SENTINEL'}]},sq_next_session:{reason:'PRIVATE_DRAFT_SENTINEL'},sq_alpha_key:'PRIVATE_KEY_SENTINEL',sq_progress:{xp:99999}});const out=JSON.stringify([...C.collect(s).values()]);assert.equal(C.collect(s).size,2);assert.doesNotMatch(out,/LOCAL_NAME|PRIVATE_JOURNAL|PRIVATE_DRAFT|PRIVATE_KEY|99999/);});
test('saved source coverage and historical context survive without fabricated metadata',()=>{const saved={id:'save1',ticker:'AAPL',p:'2y',price:100,perf:20,low:90,mid:110,high:120,inputMode:'manual',sourceContext:{source:'Synthetic fixture',session:'2026-10-07',symbol:'AAPL',stale:true,synthetic:true,coverage:{fullRange:false,weeklyGaps:2}},researchContext:{baselineDate:'2024-10-07',baselineClose:80,trend1m:'Up',sampleMonths:12}};const values=C.collect(store({splab_history:[saved]}));assert.deepEqual(values.get('saved_analysis:save1').payload,saved);});
for(const [kind,k,value]of [
 ['watchlist','AAPL',{symbol:'AAPL',journal:{reason:'PRIVATE'}}],
 ['watchlist','AAPL',{symbol:'AAPL',snapshot:{price:{journal:'PRIVATE'}}}],
 ['watchlist','AAPL',{symbol:'AAPL',name:{journal:'PRIVATE'}}],
 ['watchlist','AAPL',{symbol:'AAPL',snapshot:{sourceContext:{source:'x',coverage:{journal:'PRIVATE'}}}}],
 ['watchlist','AAPL',{symbol:'AAPL',snapshot:{symbol:'MSFT'}}],
 ['saved_analysis','save1',{id:'save1',ticker:'AAPL',sourceContext:{symbol:'MSFT'}}],
 ['saved_analysis','save1',{id:'save1',ticker:'AAPL',researchContext:{reason:'PRIVATE'}}],
 ['saved_analysis','save1',{id:'save1',ticker:'AAPL',sourceContext:{synthetic:'false'}}],
 ['milestone','first',{id:'first',at:'2026-02-31T12:00:00Z'}],
 ['journal','secret',{reason:'PRIVATE'}]
])test('reject unsupported or mistyped '+kind+' '+JSON.stringify(value).slice(0,65),()=>assert.equal(C.valid(kind,k,value),false));
test('credential scanner blocks known key values and token assignments',()=>{assert.throws(()=>C.collect(store({sq_watchlist:[item('TEST_KNOWN_SECRET_123')]}),['TEST_KNOWN_SECRET_123']));assert.throws(()=>C.secretGuard({reason:'access_token=TOKEN_FIXTURE_123'}));});
test('invalid or duplicate local identities block the whole preview',()=>{assert.throws(()=>C.collect(raw({splab_history:'{bad'})));assert.throws(()=>C.collect(store({sq_watchlist:[item(),item()]})));});
test('legacy numeric strings canonicalize only the copy',()=>{const s=store({splab_history:[{id:12,ticker:'AAPL',price:'123.45',perf:'0'}]}),before=s.getItem('splab_history');const p=C.collect(s).get('saved_analysis:12').payload;assert.equal(p.price,123.45);assert.equal(p.perf,0);assert.equal(s.getItem('splab_history'),before);});
test('empty local workspace downloads cloud; new local item uploads only in a plan',()=>{assert.equal(C.plan(local(null),remote(),new Map()).entries[0].action,'download');assert.equal(C.plan(local(),new Map(),new Map()).entries[0].action,'upload');});
test('equivalent field ordering is an identical duplicate',()=>{const l=local({name:'One',symbol:'AAPL'});assert.equal(C.plan(l,remote(),new Map()).entries.length,0);});
test('first synchronization does not overwrite independently created versions',()=>assert.equal(C.plan(local(item('Device')),remote(item('Cloud')),new Map()).entries[0].action,'conflict'));
test('one-sided local edit uploads, one-sided cloud edit downloads',()=>{const base=remote();assert.equal(C.plan(local(item('Edited')),remote(),base).entries[0].action,'upload');assert.equal(C.plan(local(),remote(item('Edited'),2),base).entries[0].action,'download');});
test('two device edits require an explicit conflict choice',()=>{const p=C.plan(local(item('Device')),remote(item('Cloud'),2),remote());assert.equal(p.entries[0].action,'conflict');assert.throws(()=>C.resolved(p));assert.equal(C.uploadRows(C.resolved(p,{'watchlist:AAPL':'upload'}),A)[0].revision,3);assert.equal(C.resolved(p,{'watchlist:AAPL':'download'})[0].action,'download');});
test('local deletions become tombstones; cloud deletion downloads rather than revives',()=>{const p=C.plan(local(null),remote(),remote());const w=C.uploadRows(C.resolved(p),A);assert.equal(w[0].deleted,true);assert.equal(w[0].payload,null);assert.equal(w[0].revision,2);assert.equal(C.plan(local(),remote(null,2,true),remote()).entries[0].action,'download');});
test('stale device without a baseline must explicitly resolve a cloud tombstone',()=>assert.equal(C.plan(local(),remote(null,2,true),new Map()).entries[0].action,'conflict'));
test('revision, owner and malformed cloud values cannot enter a plan',()=>{assert.throws(()=>C.rowsMap([record()],B));assert.throws(()=>C.rowsMap([{...record(),revision:'1'}],A));assert.throws(()=>C.rowsMap([{...record(),payload:{symbol:'AAPL',snapshot:{journal:'PRIVATE'}}}],A));assert.throws(()=>C.rowsMap([record(),record()],A));});
test('index symbols survive row validation',()=>assert.equal(C.rowsMap([{...record(),record_key:'^GSPC',payload:{symbol:'^GSPC'}}],A).size,1));
test('guest import selects differences and exposes conflicts without writes',()=>{const s=store({sq_watchlist:[item('Guest')]}),before=s.getItem('sq_watchlist'),p=C.importPlan(C.collect(s),local());assert.equal(p.entries[0].conflict,true);assert.equal(s.getItem('sq_watchlist'),before);});
test('local account merge preserves journal, nickname, input draft, metadata and exact milestone dates',()=>{const s=store({sq_research_checkins_v1:{entries:[{reason:'LOCAL_JOURNAL'}]},sq_studio_preferences_v1:{name:'Local name',theme:'quest'},sq_next_session:{price:77}}),journal=s.getItem('sq_research_checkins_v1'),draft=s.getItem('sq_next_session');C.applyLocal(s,[{kind:'appearance',record_key:'appearance',value:{theme:'quiet'}},{kind:'watchlist',record_key:'AAPL',value:item()},{kind:'milestone',record_key:'first',value:{id:'first',at,mode:'demo'}}],[record()]);assert.equal(s.getItem('sq_research_checkins_v1'),journal);assert.equal(s.getItem('sq_next_session'),draft);assert.equal(JSON.parse(s.getItem('sq_studio_preferences_v1')).name,'Local name');assert.equal(JSON.parse(s.getItem('sq_badges_v1011')).earned.first.at,at);});
test('quota failure restores prior local records and baseline',()=>{const s=store({sq_watchlist:[item('Before')],splab_history:[]}),before=Object.fromEntries(s.m),original=s.setItem;let once=true;s.setItem=(k,v)=>{if(k===C.BASE&&once){once=false;throw Error('quota');}original(k,v);};assert.throws(()=>C.applyLocal(s,[{kind:'watchlist',record_key:'AAPL',value:item('After')}],[record()]));assert.deepEqual(Object.fromEntries(s.m),before);});
test('appearance deletion preserves local nickname and remains collectable',()=>{const s=store({sq_studio_preferences_v1:{name:'Local',theme:'quiet'}});C.applyLocal(s,[{kind:'appearance',record_key:'appearance',value:null}]);assert.equal(JSON.parse(s.getItem('sq_studio_preferences_v1')).name,'Local');assert.equal(C.collect(s).size,0);});
console.log(count+' account isolation and consent-plan checks passed');
