const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),evidence=path.resolve(process.env.EVIDENCE_DIR||path.join(root,'test-results'));
let browser,server,passed=0;const report=[],errors=[];
const pass=name=>{passed++;report.push(name);console.log('PASS',name)};
function fixture(symbol){
 const price=symbol==='MSFT'?320:200,weekly=[];
 for(let i=0;i<211;i++){const c=price-(210-i)*.3;weekly.push({date:new Date(Date.UTC(2026,8,30)-(210-i)*7*86400000).toISOString().slice(0,10),close:c,high:c+5,low:c-5})}
 const monthly=Array.from({length:121},(_,i)=>({date:new Date(Date.UTC(2016,9+i,0)).toISOString().slice(0,10),close:Math.max(10,price-120+i),high:price-115+i,low:Math.max(5,price-125+i)}));
 return {ok:true,symbol,source:'Synthetic automated test fixture',cache:'hit',fetchedAt:Date.now(),latestSession:'2026-09-30',daily:[weekly.at(-1)],weekly,monthly};
}
(async()=>{
 fs.mkdirSync(evidence,{recursive:true});
 server=http.createServer((req,res)=>{const u=new URL(req.url,'http://local');const file=path.resolve(root,u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1)));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end()}res.setHeader('content-type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file))});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
 const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),requests=[];
 await context.addInitScript(()=>{localStorage.setItem('sq_alpha_key','TEST_ONLY');localStorage.setItem('splab_barchart_key','TEST_ONLY');});
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===base)return route.continue();requests.push({host:u.hostname,path:u.pathname});if(u.hostname==='strikequests-market-data.strikequests.workers.dev')return route.fulfill({contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(u.pathname==='/health'?{ok:true,cacheConfigured:true,providerConfigured:true}:fixture(u.searchParams.get('symbol')))});return route.abort()});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.waitForFunction(()=>document.getElementById('modeTitle').textContent.includes('DEMO'));
 await page.waitForTimeout(350);assert.equal(requests.length,0);pass('default demo blocks startup health, provider and search requests even with stored keys');
 assert.equal(await page.locator('.quick-pick svg').count(),11);assert.deepEqual(await page.locator('[data-quick]').evaluateAll(els=>els.map(e=>e.dataset.quick)),['AAPL','MSFT','NVDA','XLK','SPY','QQQ','SMH','AMZN','GOOGL','TSLA','VOO']);assert.match(await page.locator('.brand h1').textContent(),/StrikeQuests/);pass('all eight original Quick Picks plus three additions have local icons and correct spelling');
 assert.equal(await page.locator('#researchScore').textContent(),'0/9');assert.equal(await page.locator('#badgeGrid [data-badge]').count(),9);assert.equal(await page.locator('#badgeGrid .earned').count(),0);assert.match(await page.locator('[data-badge="review"]').getAttribute('class'),/locked/);pass('fresh browser has nine distinct core milestones and zero earned awards');
 await page.locator('[data-view="quests"]').click();await page.screenshot({path:path.join(evidence,'mobile-badges-fresh.png'),fullPage:true});await page.locator('[data-view="research"]').click();
 await page.locator('#analyzeBtn').click();assert.match(await page.locator('[data-badge="first"]').getAttribute('class'),/earned/);pass('explicit analysis earns the first milestone; startup alone does not');
 for(const ticker of ['XLK','SPY','SMH']){await page.locator(`[data-quick="${ticker}"]`).click();assert.equal(await page.locator('#ticker').inputValue(),ticker);assert.notEqual(await page.locator('#low').textContent(),'—')}
 assert.equal(requests.length,0);assert.match(await page.locator('[data-quick="XLK"]').textContent(),/Technology ETF/);assert.match(await page.locator('[data-quick="SPY"]').textContent(),/S&P 500 ETF/);assert.match(await page.locator('[data-quick="SMH"]').textContent(),/VanEck/);await page.locator('[data-quick="AAPL"]').click();pass('restored ETF choices have distinct labels and work privately');

 const sourceHigh=await page.locator('#high').textContent();const levels={};
 await page.locator('#scenarioSection').scrollIntoViewIfNeeded();
 for(const value of [0,10,30,10,0,30]){
  await page.locator('#targetCorrection').evaluate((el,v)=>{el.value=String(v);el.dispatchEvent(new Event('input',{bubbles:true}))},value);
  assert.equal(await page.locator('#correction').inputValue(),String(value));assert.equal(await page.locator('#targetCorrectionLabel').textContent(),value+'%');
  assert.equal(await page.locator('#high').textContent(),sourceHigh);
  const values=await page.evaluate(()=>({low:document.getElementById('low').textContent,mid:document.getElementById('mid').textContent,high:document.getElementById('high').textContent}));
  if(levels[value])assert.deepEqual(values,levels[value]);levels[value]=values;
 }
 assert.notEqual(levels[0].low,levels[30].low);assert.equal(levels[0].low,levels[0].high);assert.equal(requests.length,0);pass('0/10/30 input updates both sliders/prices before release; no compounding or network');
 await page.locator('#correction').evaluate(el=>{el.value='12';el.dispatchEvent(new Event('input',{bubbles:true}))});assert.equal(await page.locator('#targetCorrection').inputValue(),'12');
 await page.locator('#targetCorrection').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#correction').inputValue(),'13');assert.equal(await page.locator('#targetCorrection').getAttribute('aria-valuetext'),'13 percent correction');pass('bidirectional correction synchronization and native keyboard/aria value');
 await page.locator('#resetScenario').click();assert.equal(await page.locator('#targetCorrection').inputValue(),'10');pass('reset restores canonical correction without changing input basis');
 const horizons=[];for(const p of ['3m','6m','1y','2y','3y']){await page.locator(`[data-p="${p}"] small`).click();horizons.push(await page.evaluate(()=>state.extra.baselineDate));assert.equal(await page.locator(`[data-p="${p}"]`).getAttribute('aria-pressed'),'true');assert.match(await page.locator('#horizonBasis').textContent(),/202[0-6]-/);assert.equal(await page.evaluate(()=>calc().high===Math.ceil((calc().p+calc().perf/calc().div)/calc().inc)*calc().inc),true)}assert.equal(new Set(horizons).size,5);assert.equal(requests.length,0);pass('all five horizon labels update distinct date bases and unchanged rounded formulas without requests');
 await page.locator('[data-quick="MSFT"]').click();assert.equal(await page.locator('#price').inputValue(),'320.00');pass('ticker switch replaces the entire synthetic scenario');
 await page.locator('[data-private-mode="manual"]').click();assert.equal(await page.locator('#low').textContent(),'—');
 await page.locator('#price').fill('125');await page.locator('#perf').fill('20');await page.locator('#divisor').fill('3.5');await page.locator('#correction').evaluate(el=>{el.value='30';el.dispatchEvent(new Event('input',{bubbles:true}))});
 await page.locator('#researchReason').fill('Short');await page.locator('#saveReasonBtn').click();assert.equal(await page.locator('#researchReason').getAttribute('aria-invalid'),'true');assert.match(await page.locator('#noteValidation').textContent(),/12 characters/);assert.equal(await page.locator('#badgeGrid').textContent().then(x=>x.includes('12 characters')),false);pass('minimum note length appears inline, never on badge faces');
 await page.locator('#researchReason').fill('PRIVATE_REASON_SENTINEL: compare the history before changing assumptions.');
 await page.locator('#saveReasonBtn').click();assert.equal(await page.locator('[data-badge="saved"]').getAttribute('class'),'new-badge earned');pass('first saved reasoning unlocks an attainable badge');
 const earned=await page.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('sq_badges_v1011')).earned.saved));await page.locator('#saveReasonBtn').click();assert.equal(await page.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('sq_badges_v1011')).earned.saved)),earned);pass('repeated saving cannot duplicate badge rewards');
 await page.reload();assert.match(await page.locator('#modeTitle').textContent(),/PRIVATE MANUAL/);assert.equal(await page.locator('#price').inputValue(),'125');assert.equal(await page.locator('#targetCorrection').inputValue(),'30');assert.equal(requests.length,0);pass('manual mode, inputs, correction and reasoning restore privately on reload');
 for(const value of ['0','-20','']){await page.locator('#price').fill(value);assert.equal(await page.locator('#high').textContent(),'—');assert.match(await page.locator('#targetInvalid').textContent(),/valid inputs/)}
 await page.evaluate(()=>{document.getElementById('price').value='1e309';render()});assert.equal(await page.locator('#low').textContent(),'—');pass('zero/negative/empty/non-finite prices hide previous targets');
 await page.locator('#price').fill('125');await page.locator('#perf').fill('20');await page.locator('#ticker').fill('NVDA');await page.waitForTimeout(350);assert.equal(await page.locator('#low').textContent(),'—');assert.equal(requests.length,0);pass('manual ticker edit clears prior ticker results and blocks remote symbol lookup');
 await page.locator('[data-view="saved"]').click();await page.locator('#history button').filter({hasText:'Load'}).first().click();assert.equal(await page.locator('#price').inputValue(),'125.00');assert.equal(await page.locator('#divisor').inputValue(),'3.5');assert.equal(await page.locator('#targetCorrection').inputValue(),'30');assert.equal(requests.length,0);pass('saved analysis restores exact values/correction in private manual mode');
 const summary=await page.evaluate(()=>resultSummary());assert.match(summary,/MANUAL/);for(const s of ['TEST_ONLY','PRIVATE_REASON_SENTINEL','splab_history'])assert.equal(summary.includes(s),false);pass('share summary labels inputs and excludes keys, notes and saved history');
 await page.locator('#reviewHypothesisBtn').click();assert.match(await page.locator('[data-badge="review"]').getAttribute('class'),/earned/);pass('reviewing a loaded saved hypothesis unlocks a distinct badge');
 await page.locator('[data-private-mode="demo"]').click();await page.locator('[data-p="3m"]').click();await page.locator('[data-p="2y"]').click();
 await page.locator('.data-quality details').evaluate(el=>el.open=true);await page.locator('#reviewSampleBtn').click();assert.match(await page.locator('[data-badge="season"]').getAttribute('class'),/earned/);
 await page.locator('#researchReason').fill('Two horizons change the baseline; this is synthetic learning data.');await page.locator('#saveReasonBtn').click();assert.match(await page.locator('[data-badge="multi"]').getAttribute('class'),/earned/);pass('sample review and supported-horizon takeaway unlock distinct persisted learning badges');
 await page.locator('#reviewTrendsBtn').click();await page.locator('#reviewRangeBtn').click();assert.match(await page.locator('[data-badge="trend"]').getAttribute('class'),/earned/);assert.match(await page.locator('[data-badge="range"]').getAttribute('class'),/earned/);
 await page.locator('[data-quick="MSFT"]').click();await page.locator('#watchCurrentBtn').click();await page.locator('[data-quick="AAPL"]').click();await page.locator('#watchCurrentBtn').click();await page.locator('[data-view="watchlist"]').click();
 await page.locator('.watch-item').filter({hasText:'MSFT'}).getByRole('button',{name:'Compare',exact:true}).click();await page.locator('.watch-item').filter({hasText:'AAPL'}).getByRole('button',{name:'Compare',exact:true}).click();
 assert.match(await page.locator('[data-badge="watch"]').getAttribute('class'),/earned/);assert.match(await page.locator('[data-badge="compare"]').getAttribute('class'),/earned/);await page.locator('[data-view="quests"]').click();await page.locator('#completeResearchBtn').click();assert.equal(await page.locator('#researchScore').textContent(),'9/9');pass('trend, range, watchlist and side-by-side tasks lead to an explicit full research run');
 await page.reload();assert.equal(await page.locator('#researchScore').textContent(),'9/9');assert.match(await page.locator('[data-badge="review"]').getAttribute('class'),/earned/);pass('earned core and reflection milestones persist across browser reload');
 await page.waitForFunction(()=>getComputedStyle(document.getElementById('badgeToast')).opacity==='0');

 const monthChecks=await page.evaluate(()=>({missing:computeSeasonality([]),gap:computeSeasonality([{date:'2025-01-31',close:100},{date:'2025-03-31',close:110}],10),zero:computeSeasonality([{date:'2025-01-31',close:0},{date:'2025-02-28',close:110}],10),one:computeSeasonality([{date:'2025-01-31',close:100},{date:'2025-02-28',close:110}],10)?.months[1].observations}));assert.equal(monthChecks.missing,null);assert.equal(monthChecks.gap,null);assert.equal(monthChecks.zero,null);assert.equal(monthChecks.one,1);pass('missing/gapped/zero-price monthly data is unavailable, not a fabricated zero return');
 const invalid=await page.evaluate(()=>{const tests=[()=>sqValidateRaw({daily:[],weekly:[],monthly:[]},'AAPL'),()=>sqValidateRaw({...sqSynthetic('AAPL'),symbol:'MSFT'},'AAPL'),()=>sqValidateRaw({...sqSynthetic('AAPL'),daily:[{date:'2026-09-30',close:0}]},'AAPL'),()=>sqValidateRaw({...sqSynthetic('AAPL'),daily:[{date:'2026-09-30',close:200,high:100,low:300}]},'AAPL')];return tests.map(fn=>{try{fn();return false}catch{return true}})});assert.deepEqual(invalid,[true,true,true,true]);pass('schema rejects incomplete, mismatched-symbol, zero-price and inverted-range payloads');
 // Rendered mobile target section: all cards + lower slider fit above the nav.
 await page.locator('[data-p="1y"]').click();await page.locator('#resetScenario').click();await page.locator('#scenarioSection').evaluate(el=>el.scrollIntoView({block:'start'}));
 const geometry=await page.evaluate(()=>({top:document.getElementById('targetsRow').getBoundingClientRect().top,bottom:document.getElementById('targetCorrection').getBoundingClientRect().bottom,nav:document.querySelector('.bottom-nav').getBoundingClientRect().top,overflow:document.documentElement.scrollWidth>innerWidth}));assert.equal(geometry.overflow,false);assert.ok(geometry.top>=0&&geometry.bottom<geometry.nav,JSON.stringify(geometry));pass('390px mobile shows all target prices and correction slider above fixed navigation');
 await page.screenshot({path:path.join(evidence,'mobile-targets-demo.png')});
 await page.locator('#correction').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(evidence,'mobile-horizons-demo.png')});
 await page.locator('.quick-card').evaluate(el=>el.scrollIntoView({block:'start'}));await page.screenshot({path:path.join(evidence,'mobile-quick-picks.png')});
 await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(evidence,'mobile-top-demo.png')});await page.screenshot({path:path.join(evidence,'mobile-overview-demo.png'),fullPage:true});
 await page.locator('[data-view="quests"]').click();await page.screenshot({path:path.join(evidence,'mobile-badges-earned.png'),fullPage:true});
 await page.locator('#badgeGrid').evaluate(el=>el.scrollIntoView({block:'start'}));await page.screenshot({path:path.join(evidence,'mobile-badge-grid.png')});
 await page.locator('[data-view="research"]').click();await page.setViewportSize({width:1440,height:1050});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(evidence,'desktop-demo.png'),fullPage:true});
 await page.locator('[data-view="quests"]').click();await page.locator('#badgeGrid').screenshot({path:path.join(evidence,'desktop-nine-badges-earned.png')});await page.locator('[data-view="research"]').click();
 await page.locator('#scenarioSection').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(evidence,'desktop-controls-demo.png')});
 await page.setViewportSize({width:320,height:700});const zoomStyle=await page.addStyleTag({content:'body{font-size:200%} .target .tier,.target-detail,.correction-label,.scenario-note{font-size:1em}'});await page.locator('#targetCorrection').scrollIntoViewIfNeeded();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('#targetCorrection').evaluate(el=>{const r=el.getBoundingClientRect(),nav=document.querySelector('.bottom-nav').getBoundingClientRect();return r.top>=0&&r.bottom<nav.top}),true);pass('320px enlarged-text controls remain reachable without horizontal overflow or nav obstruction');
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('#badgeToast').evaluate(el=>getComputedStyle(el).transitionDuration),'0s');pass('reduced-motion preference removes badge toast animation');
 await zoomStyle.evaluate(el=>el.remove());await page.locator('[data-private-mode="manual"]').click();await page.locator('#price').fill('12345.67');await page.locator('#perf').fill('1200');await page.locator('#increment').selectOption('0.5');
 for(const width of [320,360,390])for(const price of ['1000.25','12345.67','999999.99']){await page.setViewportSize({width,height:width===320?700:844});await page.locator('#price').fill(price);await page.locator('#scenarioSection').evaluate(el=>el.scrollIntoView({block:'start'}));const x=await page.locator('#targetsRow').evaluate(el=>({overflow:[...el.querySelectorAll('.n')].some(n=>n.scrollWidth>n.clientWidth+1),large:[...el.querySelectorAll('.n')].every(n=>parseFloat(getComputedStyle(n).fontSize)>=32),page:document.documentElement.scrollWidth>innerWidth,top:el.getBoundingClientRect().top,slider:document.getElementById('targetCorrection').getBoundingClientRect().bottom,nav:document.querySelector('.bottom-nav').getBoundingClientRect().top}));assert.equal(x.overflow,false,JSON.stringify({width,price,...x}));if(x.page)console.log('OVERFLOW_DIAGNOSTIC',JSON.stringify(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,15).map(e=>({tag:e.tagName,id:e.id,class:e.getAttribute('class'),right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width})))));assert.equal(x.page,false,JSON.stringify({width,price,...x}));assert.equal(x.large,true);assert.ok(x.top>=0&&x.slider<x.nav,JSON.stringify({width,price,...x}))}pass('prominent prices from four to six digits and decimals fit at 320/360/390px with the slider visible');
 await page.locator('#price').fill('12345.67');await page.locator('#scenarioSection').evaluate(el=>el.scrollIntoView({block:'start'}));await page.screenshot({path:path.join(evidence,'mobile-large-values-manual.png')});
 await context.close();
 // Automatic behavior is explicitly chosen and all remote traffic is mocked.
 const auto=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),autoCalls=[];let bad=false;
 await auto.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===base)return route.continue();autoCalls.push(u.pathname);const body=u.pathname==='/health'?{ok:true,cacheConfigured:true,providerConfigured:true}:bad?{...fixture('AAPL'),symbol:'WRONG'}:fixture(u.searchParams.get('symbol'));return route.fulfill({contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(body)})});
 const ap=await auto.newPage();ap.on('pageerror',e=>errors.push(e.message));await ap.goto(base);await ap.locator('[data-private-mode="auto_eod"]').click();await ap.waitForFunction(()=>document.getElementById('status').textContent.includes('shared EOD loaded'));
 assert.equal(await ap.locator('#price').inputValue(),'200.00');assert.match(await ap.locator('#qualitySummary').textContent(),/session 2026-09-30/);pass('explicit Automatic mode retains shared loading and source/session metadata with mocks');
 const n=autoCalls.length;await ap.locator('#targetCorrection').evaluate(el=>{el.value='30';el.dispatchEvent(new Event('input',{bubbles:true}))});assert.equal(autoCalls.length,n);pass('correction dragging never fetches even in Automatic mode');
 bad=true;await ap.locator('[data-quick="MSFT"]').click();await ap.waitForFunction(()=>document.getElementById('status').textContent.includes('Manual inputs'));assert.equal(await ap.locator('#low').textContent(),'—');pass('wrong-symbol response cannot reuse another ticker’s targets');
 await auto.close();
 // Installed app shell: prove a real SW offline reload has no provider requests.
 const offline=await browser.newContext({viewport:{width:390,height:844}}),external=[];
 await offline.route('https://**/*',r=>{external.push(new URL(r.request().url()).hostname);return r.abort()});
 const op=await offline.newPage();op.on('pageerror',e=>errors.push(e.message));await op.goto(base);await op.evaluate(()=>navigator.serviceWorker.ready);await op.reload();await op.waitForFunction(()=>!!navigator.serviceWorker.controller);
 const keys=await op.evaluate(async()=>{const c=await caches.open('strikequests-v10-1-4-lumi-taps');return (await c.keys()).map(r=>r.url)});assert.equal(keys.length,9);assert.equal(keys.some(x=>x.includes('?')||x.includes('workers.dev')),false);
 await offline.setOffline(true);await op.reload();assert.match(await op.locator('#modeTitle').textContent(),/DEMO/);await op.locator('#targetCorrection').evaluate(el=>{el.value='30';el.dispatchEvent(new Event('input',{bubbles:true}))});assert.equal(await op.locator('#correction').inputValue(),'30');assert.deepEqual(external,[]);pass('offline shell restores functional private demo with zero provider/health/search requests');
 await offline.close();assert.deepEqual(errors,[]);pass('no uncaught browser errors across rendered flows');
 fs.writeFileSync(path.join(evidence,'next-build-results.json'),JSON.stringify({passed,checks:report,externalRequestsInPrivateModes:0,liveProviderRequests:0,automaticRequestsMocked:autoCalls,errors},null,2));
 console.log(`${passed} next-build browser checks passed; no live market provider contacted.`);
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r))});
