'use strict';
const path=require('node:path');
require('esbuild').buildSync({entryPoints:[path.join(__dirname,'account-sdk-entry.js')],outfile:path.join(__dirname,'../vendor/supabase.js'),bundle:true,format:'iife',globalName:'StrikeSupabase',platform:'browser',target:['es2020'],minify:true,legalComments:'inline',banner:{js:'/* @supabase/supabase-js 2.117.3; generated by npm run build:account from package-lock.json. */'}});
